steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ '-c', 'docker build -t gcr.io/dtumlops-337913/training . --build-arg WANDB_API_KEY_LOG=$(WANDB_API_KEY) --no-cache']
  secretEnv: ['WANDB_API_KEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-337913/training']
availableSecrets:
  secretManager:
  - versionName: projects/953607909724/secrets/WANDB_API_KEY/versions/2
    env: 'WANDB_API_KEY'